# Set the desired connector (e.g. MongoDB)
Source:
    MongoDB:
        host: localhost
        port: 27017
        db: recommender_dev

User:
    export: true
    #from: 'user_actions'
    #from: 'recommendations'
    from: 'source'

Service:
    # Use the EOSC-Marketplace webpage
    # to associate page_id and service_id
    download: true
    path: ./page_map

    export: true
    #from: 'user_actions'
    #from: 'recommendations'
    #from: 'source'
    from: 'page_map'

    published: true # applies only on source option

# Calculate source's metrics
Metrics: true




