# Set the desired connector (e.g. MongoDB)
Source:
    MongoDB:
        host: localhost
        port: 27017
        db: recommender_dev

User:
    export: true

Service:
    # if true it keeps only published, otherwise all
    # this has an effect in exporting when from is set to 'source' 
    # and also in metrics calculations where service is considered
    published: false

    # Use the EOSC-Marketplace webpage
    # to associate page_id and service_id
    download: true
    path: ./page_map

    export: true
    from: 'page_map' # or 'source'

# Calculate source's metrics
Metrics: true




